export const BASE_BE = "http://localhost:4000/api/";

export const Message = {
  TAI_KHOAN_TON_TAI: "TAI_KHOAN_TON_TAI",
  DANG_KY_THANH_CONG: "DANG_KY_THANH_CONG",
  DANG_NHAP_THANH_CONG: "DANG_NHAP_THANH_CONG",
  LOI_SERVER: "LOI_SERVER",
  TAI_KHOAN_OR_MK_SAI: "TAI_KHOAN_OR_MK_SAI",
  KHONG_CO_QUYEN_TRUY_CAP: "KHONG_CO_QUYEN_TRUY_CAP",
  CO_LOI_KHI_DANG_NHAP: "CO_LOI_KHI_DANG_NHAP",
  THANH_CONG: "THANH CONG"
}